# Use root/example as user/password credentials
version: "3.1"

services:
  quickflix:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: db_quickflix
    volumes:
      - ./data/:/data/db
    ports:
      - 27018:27017


