# Use root/example as user/password credentials
version: "3.1"

services:
  quickflix:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: db_quickflix
    volumes:
      - ./data/:/data/db
    ports:
      - 27017:27017

  quickflix-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
